# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-15 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conley', '0002_auto_20161115_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_date',
            field=models.DateField(null=True),
        ),
    ]
