# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-15 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conley', '0004_auto_20161115_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
